###########
# site.title

title:    'SCUBA DIVER'
subtitle: 'An under-the-sea adventure with double Q-learning!'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
